                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ?column?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE active_mesocycle (notes text, status text, start_date date, created_at timestamp with time zone, focus text, name text, end_date date, id uuid);
 CREATE TABLE cycling_sessions (hr_zone_2_s integer, hr_zone_1_s integer, training_effect_anaerobic numeric, training_effect_aerobic numeric, max_power_w integer, avg_power_w integer, max_cadence_rpm integer, notes text, avg_cadence_rpm integer, elevation_loss_m numeric, elevation_gain_m numeric, external_id text, calories integer, max_speed_kmh numeric, avg_speed_kmh numeric, min_heart_rate integer, max_heart_rate integer, avg_heart_rate integer, source text DEFAULT 'garmin'::text, cycling_type text, distance_m numeric, duration_s numeric, started_at timestamp with time zone, ended_at timestamp with time zone, date date NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), raw_garmin jsonb, hr_zone_5_s integer, hr_zone_4_s integer, hr_zone_3_s integer);
 CREATE TABLE exercise_progression (date date, mesocycle_name text, exercise text, reps_at_max_weight integer, max_weight_kg numeric, week_number integer, exercise_id uuid);
 CREATE TABLE exercises (notes text, movement_pattern text, equipment text, muscle_group text, name text NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now());
 CREATE TABLE garmin_daily_summaries (stress_low_s integer, stress_medium_s integer, stress_high_s integer, stress_max integer, stress_avg integer, vo2_max numeric, training_load_28d numeric, training_load_7d numeric, training_readiness_activity_score numeric, training_status text, raw_training_readiness jsonb, raw_body_battery jsonb, raw_hrv jsonb, raw_sleep jsonb, avg_respiration_rate numeric, resting_heart_rate integer, stress_rest_s integer, hrv_status text, sedentary_seconds integer, active_seconds integer, total_steps integer, measurable_awake_s integer, measurable_asleep_s integer, seven_day_avg_rhr integer, min_heart_rate integer, body_battery_during_sleep integer, updated_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now(), raw_respiration jsonb, training_readiness_recovery_score numeric, training_readiness_sleep_score numeric, training_readiness_hrv_score numeric, training_readiness_score integer, body_battery_low integer, body_battery_high integer, body_battery_morning integer, hrv_last_night numeric, hrv_weekly_avg numeric, sleep_awake_s integer, sleep_rem_s integer, sleep_light_s integer, sleep_deep_s integer, sleep_score integer, sleep_duration_s integer, summary_date date NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), training_readiness_level text, raw_daily_summary jsonb, raw_stress jsonb, raw_training_status jsonb);
 CREATE TABLE garmin_sync_log (status text NOT NULL, created_at timestamp with time zone DEFAULT now(), details jsonb, duration_ms integer, sync_date date, id uuid NOT NULL DEFAULT gen_random_uuid(), sync_type text NOT NULL, error_message text);
 CREATE TABLE garmin_tokens (id uuid NOT NULL DEFAULT gen_random_uuid(), oauth2_access_token text NOT NULL, consumer_key text NOT NULL, consumer_secret text NOT NULL, updated_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now(), oauth1_created_at timestamp with time zone DEFAULT now(), oauth2_expires_at bigint NOT NULL, oauth1_token text NOT NULL, display_name text NOT NULL, oauth1_token_secret text NOT NULL);
 CREATE TABLE goals (target_date date, notes text, target_reps integer, created_at timestamp with time zone DEFAULT now(), mesocycle_id uuid, exercise_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), target_value numeric NOT NULL, goal_type text NOT NULL, achieved_at timestamp with time zone);
 CREATE TABLE mesocycle_days (name text NOT NULL, created_at timestamp with time zone DEFAULT now(), day_number integer NOT NULL, mesocycle_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), notes text);
 CREATE TABLE mesocycle_planned_exercises (id uuid NOT NULL DEFAULT gen_random_uuid(), mesocycle_day_id uuid, exercise_id uuid, exercise_order integer NOT NULL, target_sets integer, target_rpe numeric, created_at timestamp with time zone DEFAULT now(), target_reps text, notes text);
 CREATE TABLE mesocycles (rpe_start integer DEFAULT 7, start_date date NOT NULL, end_date date, name text NOT NULL, focus text, status text DEFAULT 'active'::text, created_at timestamp with time zone DEFAULT now(), rpe_end integer DEFAULT 10, progression_style text DEFAULT 'auto'::text, id uuid NOT NULL DEFAULT gen_random_uuid(), priority_muscles ARRAY, notes text);
 CREATE TABLE run_hr_zones (duration_s numeric, min_hr integer, zone_number integer NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), max_hr integer, run_session_id uuid NOT NULL, created_at timestamp with time zone DEFAULT now());
 CREATE TABLE run_laps (lap_number integer NOT NULL, duration_s numeric, avg_pace_s_per_km numeric, avg_heart_rate integer, max_cadence integer, max_heart_rate integer, avg_cadence integer, elevation_gain_m numeric, avg_stride_length_m numeric, elevation_loss_m numeric, created_at timestamp with time zone DEFAULT now(), id uuid NOT NULL DEFAULT gen_random_uuid(), run_session_id uuid NOT NULL, distance_m numeric);
 CREATE TABLE run_sessions (target_cadence_spm integer, target_hr_min integer, target_hr_max integer, id uuid NOT NULL DEFAULT gen_random_uuid(), date date NOT NULL, started_at timestamp with time zone, ended_at timestamp with time zone, distance_m numeric, duration_s numeric, avg_pace_s_per_km numeric, source text DEFAULT 'manual'::text, notes text, avg_heart_rate integer, external_id text, max_heart_rate integer, avg_cadence integer, elevation_gain_m numeric, mesocycle_id uuid, created_at timestamp with time zone DEFAULT now(), min_heart_rate integer, max_cadence integer, avg_stride_length_m numeric, steps integer, run_type text, avg_temperature_c numeric, moving_duration_s numeric, fastest_1km_s numeric, fastest_mile_s numeric, fastest_5km_s numeric, raw_garmin jsonb, sleep_quality integer, energy_level integer, muscle_soreness jsonb, target_pace_s_per_km numeric, elevation_loss_m numeric, calories integer, training_effect_aerobic numeric, training_effect_anaerobic numeric, vo2_max_estimate numeric, perceived_effort integer);
 CREATE TABLE strava_sync_log (error_message text, id uuid NOT NULL DEFAULT gen_random_uuid(), strava_activity_id bigint NOT NULL, run_session_id uuid, raw_payload jsonb, created_at timestamp with time zone DEFAULT now(), event_type text NOT NULL, status text NOT NULL);
 CREATE TABLE strava_tokens (access_token text NOT NULL, athlete_json jsonb, refresh_token text NOT NULL, scope text, id uuid NOT NULL DEFAULT gen_random_uuid(), athlete_id bigint NOT NULL, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), expires_at bigint NOT NULL);
 CREATE TABLE strava_webhook_subscriptions (id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), subscription_id bigint NOT NULL, callback_url text NOT NULL);
 CREATE TABLE superset_groups (name text, created_at timestamp with time zone DEFAULT now(), workout_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid());
 CREATE TABLE weekly_run_targets (duration_min integer, week_number integer NOT NULL, mesocycle_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp without time zone DEFAULT now(), interval_pace_text text, target_cadence_spm integer, distance_km numeric, target_hr_text text, notes text, run_type text NOT NULL, day_of_week text NOT NULL, interval_distance_m integer, cooldown_text text, intervals_count integer, target_pace_text text, warmup_text text, recovery_text text);
 CREATE TABLE weekly_targets (target_weight_kg numeric, notes text, week_number integer NOT NULL, target_rpe text, rest_seconds integer, id uuid NOT NULL DEFAULT gen_random_uuid(), mesocycle_day_id uuid, mesocycle_id uuid, exercise_id uuid, exercise_order integer NOT NULL, created_at timestamp with time zone DEFAULT now(), superset_group text, target_sets integer NOT NULL, target_reps text NOT NULL);
 CREATE TABLE weekly_volume_by_muscle (total_volume_kg numeric, mesocycle_name text, muscle_group text, mesocycle_id uuid, total_sets bigint, week_number integer);
 CREATE TABLE workout_exercise_notes (notes text NOT NULL, joint_discomfort integer, workout_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), pump_quality integer, created_at timestamp with time zone DEFAULT now(), exercise_id uuid);
 CREATE TABLE workout_log (weight_kg numeric, movement_pattern text, equipment text, muscle_group text, exercise text, workout_notes text, day_name text, mesocycle_focus text, exercise_notes text, superset_group_id uuid, set_notes text, set_type text, mesocycle_name text, mesocycle_id uuid, date date, workout_id uuid, set_order integer, week_number integer, workout_rating integer, exercise_id uuid, rpe numeric, reps integer);
 CREATE TABLE workout_sets (superset_group_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), notes text, workout_id uuid, exercise_id uuid, set_order integer NOT NULL, weight_kg numeric, reps integer, weight_added_kg numeric, set_type text, rpe numeric, created_at timestamp with time zone DEFAULT now());
 CREATE TABLE workout_volume_by_muscle (date date, total_volume_kg numeric, muscle_group text, workout_id uuid, total_sets bigint);
 CREATE TABLE workouts (rating integer, week_number integer, mesocycle_day_id uuid, mesocycle_id uuid, pre_session_notes text, id uuid NOT NULL DEFAULT gen_random_uuid(), ended_at timestamp with time zone, muscle_soreness jsonb, started_at timestamp with time zone, notes text, energy_level integer, date date NOT NULL DEFAULT CURRENT_DATE, sleep_quality integer, created_at timestamp with time zone DEFAULT now());
(26 rows)

