                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ?column?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE active_mesocycle (created_at timestamp with time zone, end_date date, start_date date, id uuid, focus text, name text, status text, notes text);
 CREATE TABLE exercise_progression (reps_at_max_weight integer, week_number integer, date date, exercise_id uuid, exercise text, mesocycle_name text, max_weight_kg numeric);
 CREATE TABLE exercises (created_at timestamp with time zone DEFAULT now(), equipment text, movement_pattern text, notes text, muscle_group text, name text NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid());
 CREATE TABLE garmin_daily_summaries (hrv_status text, sleep_duration_s integer, summary_date date NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), raw_respiration jsonb, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), body_battery_during_sleep integer, min_heart_rate integer, seven_day_avg_rhr integer, measurable_asleep_s integer, measurable_awake_s integer, total_steps integer, active_seconds integer, sedentary_seconds integer, body_battery_morning integer, body_battery_high integer, body_battery_low integer, training_readiness_score integer, training_readiness_hrv_score numeric, training_readiness_sleep_score numeric, training_readiness_recovery_score numeric, training_readiness_activity_score numeric, training_load_7d numeric, training_load_28d numeric, vo2_max numeric, stress_avg integer, stress_max integer, stress_high_s integer, stress_medium_s integer, stress_low_s integer, stress_rest_s integer, resting_heart_rate integer, avg_respiration_rate numeric, raw_sleep jsonb, raw_hrv jsonb, raw_body_battery jsonb, raw_training_readiness jsonb, raw_training_status jsonb, raw_stress jsonb, raw_daily_summary jsonb, training_readiness_level text, training_status text, hrv_last_night numeric, hrv_weekly_avg numeric, sleep_awake_s integer, sleep_rem_s integer, sleep_light_s integer, sleep_deep_s integer, sleep_score integer);
 CREATE TABLE garmin_sync_log (duration_ms integer, sync_date date, error_message text, sync_type text NOT NULL, status text NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), details jsonb);
 CREATE TABLE garmin_tokens (oauth2_expires_at bigint NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), display_name text NOT NULL, oauth1_token text NOT NULL, oauth1_token_secret text NOT NULL, oauth2_access_token text NOT NULL, consumer_key text NOT NULL, consumer_secret text NOT NULL, updated_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now(), oauth1_created_at timestamp with time zone DEFAULT now());
 CREATE TABLE goals (goal_type text NOT NULL, mesocycle_id uuid, notes text, target_value numeric NOT NULL, target_reps integer, target_date date, id uuid NOT NULL DEFAULT gen_random_uuid(), exercise_id uuid, achieved_at timestamp with time zone, created_at timestamp with time zone DEFAULT now());
 CREATE TABLE mesocycle_days (day_number integer NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), notes text, name text NOT NULL, mesocycle_id uuid);
 CREATE TABLE mesocycle_planned_exercises (target_rpe numeric, target_reps text, notes text, id uuid NOT NULL DEFAULT gen_random_uuid(), mesocycle_day_id uuid, created_at timestamp with time zone DEFAULT now(), exercise_id uuid, exercise_order integer NOT NULL, target_sets integer);
 CREATE TABLE mesocycles (progression_style text DEFAULT 'auto'::text, created_at timestamp with time zone DEFAULT now(), priority_muscles ARRAY, notes text, status text DEFAULT 'active'::text, start_date date NOT NULL, rpe_start integer DEFAULT 7, end_date date, rpe_end integer DEFAULT 10, name text NOT NULL, focus text, id uuid NOT NULL DEFAULT gen_random_uuid());
 CREATE TABLE run_hr_zones (zone_number integer NOT NULL, run_session_id uuid NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), min_hr integer, duration_s numeric, max_hr integer);
 CREATE TABLE run_laps (run_session_id uuid NOT NULL, elevation_gain_m numeric, lap_number integer NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), distance_m numeric, duration_s numeric, avg_heart_rate integer, avg_pace_s_per_km numeric, max_heart_rate integer, avg_stride_length_m numeric, avg_cadence integer, elevation_loss_m numeric, created_at timestamp with time zone DEFAULT now(), max_cadence integer);
 CREATE TABLE run_sessions (fastest_5km_s numeric, id uuid NOT NULL DEFAULT gen_random_uuid(), date date NOT NULL, started_at timestamp with time zone, ended_at timestamp with time zone, distance_m numeric, duration_s numeric, avg_pace_s_per_km numeric, avg_heart_rate integer, max_heart_rate integer, avg_cadence integer, elevation_gain_m numeric, elevation_loss_m numeric, calories integer, training_effect_aerobic numeric, training_effect_anaerobic numeric, vo2_max_estimate numeric, perceived_effort integer, mesocycle_id uuid, created_at timestamp with time zone DEFAULT now(), min_heart_rate integer, max_cadence integer, avg_stride_length_m numeric, steps integer, avg_temperature_c numeric, moving_duration_s numeric, fastest_1km_s numeric, fastest_mile_s numeric, raw_garmin jsonb, sleep_quality integer, energy_level integer, muscle_soreness jsonb, notes text, source text DEFAULT 'manual'::text, run_type text, external_id text);
 CREATE TABLE strava_sync_log (event_type text NOT NULL, created_at timestamp with time zone DEFAULT now(), raw_payload jsonb, run_session_id uuid, strava_activity_id bigint NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), error_message text, status text NOT NULL);
 CREATE TABLE strava_tokens (created_at timestamp with time zone DEFAULT now(), id uuid NOT NULL DEFAULT gen_random_uuid(), refresh_token text NOT NULL, access_token text NOT NULL, athlete_id bigint NOT NULL, scope text, expires_at bigint NOT NULL, athlete_json jsonb, updated_at timestamp with time zone DEFAULT now());
 CREATE TABLE strava_webhook_subscriptions (id uuid NOT NULL DEFAULT gen_random_uuid(), subscription_id bigint NOT NULL, callback_url text NOT NULL, created_at timestamp with time zone DEFAULT now());
 CREATE TABLE superset_groups (workout_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), name text, created_at timestamp with time zone DEFAULT now());
 CREATE TABLE weekly_targets (exercise_id uuid, exercise_order integer NOT NULL, target_weight_kg numeric, target_sets integer NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), superset_group text, notes text, mesocycle_id uuid, target_reps text NOT NULL, created_at timestamp with time zone DEFAULT now(), week_number integer NOT NULL, mesocycle_day_id uuid);
 CREATE TABLE weekly_volume_by_muscle (mesocycle_name text, total_volume_kg numeric, total_sets bigint, week_number integer, mesocycle_id uuid, muscle_group text);
 CREATE TABLE workout_exercise_notes (pump_quality integer, id uuid NOT NULL DEFAULT gen_random_uuid(), exercise_id uuid, joint_discomfort integer, notes text NOT NULL, workout_id uuid, created_at timestamp with time zone DEFAULT now());
 CREATE TABLE workout_log (exercise text, week_number integer, set_notes text, workout_id uuid, mesocycle_id uuid, rpe numeric, superset_group_id uuid, date date, exercise_notes text, weight_kg numeric, set_order integer, exercise_id uuid, set_type text, workout_rating integer, movement_pattern text, muscle_group text, mesocycle_name text, mesocycle_focus text, day_name text, equipment text, workout_notes text, reps integer);
 CREATE TABLE workout_sets (set_type text, weight_kg numeric, reps integer, notes text, superset_group_id uuid, workout_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), set_order integer NOT NULL, rpe numeric, exercise_id uuid);
 CREATE TABLE workout_volume_by_muscle (muscle_group text, workout_id uuid, date date, total_sets bigint, total_volume_kg numeric);
 CREATE TABLE workouts (sleep_quality integer, rating integer, week_number integer, ended_at timestamp with time zone, started_at timestamp with time zone, date date NOT NULL DEFAULT CURRENT_DATE, mesocycle_day_id uuid, mesocycle_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), pre_session_notes text, notes text, muscle_soreness jsonb, energy_level integer, created_at timestamp with time zone DEFAULT now());
(24 rows)

