                                                                                                                                                                                                                   ?column?                                                                                                                                                                                                                   
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE active_mesocycle (notes text, id uuid, start_date date, status text, focus text, name text, end_date date, created_at timestamp with time zone);
 CREATE TABLE exercise_progression (mesocycle_name text, exercise_id uuid, date date, week_number integer, max_weight_kg numeric, reps_at_max_weight integer, exercise text);
 CREATE TABLE exercises (id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), muscle_group text, name text NOT NULL, notes text, movement_pattern text, equipment text);
 CREATE TABLE goals (target_reps integer, goal_type text NOT NULL, notes text, created_at timestamp with time zone DEFAULT now(), achieved_at timestamp with time zone, id uuid NOT NULL DEFAULT gen_random_uuid(), exercise_id uuid, mesocycle_id uuid, target_value numeric NOT NULL, target_date date);
 CREATE TABLE mesocycle_days (name text NOT NULL, created_at timestamp with time zone DEFAULT now(), notes text, mesocycle_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), day_number integer NOT NULL);
 CREATE TABLE mesocycle_planned_exercises (created_at timestamp with time zone DEFAULT now(), target_rpe numeric, exercise_order integer NOT NULL, target_sets integer, exercise_id uuid, mesocycle_day_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid(), target_reps text, notes text);
 CREATE TABLE mesocycles (id uuid NOT NULL DEFAULT gen_random_uuid(), start_date date NOT NULL, end_date date, created_at timestamp with time zone DEFAULT now(), name text NOT NULL, focus text, status text DEFAULT 'active'::text, notes text);
 CREATE TABLE superset_groups (id uuid NOT NULL DEFAULT gen_random_uuid(), workout_id uuid, name text, created_at timestamp with time zone DEFAULT now());
 CREATE TABLE weekly_targets (superset_group text, target_reps text NOT NULL, notes text, exercise_order integer NOT NULL, week_number integer NOT NULL, exercise_id uuid, mesocycle_day_id uuid, created_at timestamp with time zone DEFAULT now(), target_weight_kg numeric, target_sets integer NOT NULL, mesocycle_id uuid, id uuid NOT NULL DEFAULT gen_random_uuid());
 CREATE TABLE weekly_volume_by_muscle (mesocycle_name text, mesocycle_id uuid, week_number integer, total_sets bigint, total_volume_kg numeric, muscle_group text);
 CREATE TABLE workout_exercise_notes (notes text NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), workout_id uuid, created_at timestamp with time zone DEFAULT now(), exercise_id uuid);
 CREATE TABLE workout_log (set_notes text, mesocycle_id uuid, workout_id uuid, date date, week_number integer, workout_rating integer, exercise_id uuid, set_order integer, weight_kg numeric, reps integer, rpe numeric, superset_group_id uuid, mesocycle_name text, mesocycle_focus text, day_name text, workout_notes text, exercise text, muscle_group text, equipment text, movement_pattern text, set_type text, exercise_notes text);
 CREATE TABLE workout_sets (rpe numeric, set_type text, weight_kg numeric, workout_id uuid, reps integer, exercise_id uuid, notes text, superset_group_id uuid, set_order integer NOT NULL, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now());
 CREATE TABLE workout_volume_by_muscle (muscle_group text, workout_id uuid, total_volume_kg numeric, total_sets bigint, date date);
 CREATE TABLE workouts (date date NOT NULL DEFAULT CURRENT_DATE, notes text, rating integer, id uuid NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone DEFAULT now(), pre_session_notes text, mesocycle_day_id uuid, week_number integer, ended_at timestamp with time zone, started_at timestamp with time zone, mesocycle_id uuid);
(15 rows)

